[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = '''
            default-src 'self' 'unsafe-inline';
            font-src 'self' fonts.gstatic.com;
            style-src 'self' 'unsafe-inline' fonts.googleapis.com'''
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"

[[plugins]]
    package = "netlify-plugin-checklinks"

    [plugins.inputs]
        skipPatterns = ['https://fonts.gstatic.com']

[[plugins]]
    package = "@netlify/plugin-lighthouse"

    [plugins.inputs.thresholds]
        performance = 0.7
        # accessibility = 0.9
        best-practices = 0.9
        seo = 0.7

    [[plugins.inputs.audits]]
        path = "/"

    [[plugins.inputs.audits]]
        path = "blog/generating-random-data"
