[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self';font-src fonts.gstatic.com;style-src 'self' fonts.googleapis.com"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"

[[plugins]]
    package = "netlify-plugin-checklinks"

    [plugins.inputs]
        skipPatterns = ['https://fonts.gstatic.com']
